#!/usr/bin/env node

const { exec } = require('child_process');

/**
 * Main function.
 */
async function main() {

    const args = process.argv.slice(2)

    if (args.length != 1) {
        console.error(`
            Missing parameter.
            Usage: kseal-decode SECRET
        `)
        process.exit(1)
    }

    const secret = args[0]

    const stdout = await execShellCommand(`kubectl get secret ${secret} -o json`);

    getSecretResp = JSON.parse(stdout)
    keys = Object.keys(getSecretResp.data)


    decoded = {}
    keys.forEach(key => {
        value = getSecretResp.data[key]

        decoded[key] = atob(value)
    })
    console.log(JSON.stringify(decoded))

}

/**
 * Executes a shell command and return it as a Promise.
 * @param cmd {string}
 * @return {Promise<string>}
 */
function execShellCommand(cmd) {
 return new Promise((resolve, reject) => {
  exec(cmd, (error, stdout, stderr) => {
   if (error) {
    console.error(error);
    process.exit(1)
   }
   resolve(stdout? stdout : stderr);
  });
 });
}

main()
